name: Generate monthly

on:
  workflow_dispatch:

jobs:
  generate-monthly:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create or checkout branch
        run: |
          BRANCH_NAME="update-monthly"

          # Delete remote branch if it exists to start fresh
          git push origin --delete "$BRANCH_NAME" || true

          # Create fresh branch from master
          git checkout -b "$BRANCH_NAME"

          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Generate monthly
        run: python generate_monthly.py

      - name: Commit and push changes
        run: |
          git add monthly.json

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update monthly.json"
          fi

          # Push the fresh branch
          git push -u origin "$BRANCH_NAME"

      - name: Create or update Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_NUMBER=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[0].number')

          PR_BODY="**Updated monthly winners**

          This PR updates the monthly.json file with the winners and Hopfenhirn des Monats from the latest event.

          ---
          *Automatically generated by GitHub Actions*"

          if [ -n "$PR_NUMBER" ]; then
            echo "Updating existing PR #$PR_NUMBER"
            gh pr edit "$PR_NUMBER" --body "$PR_BODY"
          else
            echo "Creating new PR"
            gh pr create \
              --title "Update monthly.json" \
              --body "$PR_BODY" \
              --base master
          fi
