name: Generate stats

on:
  workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create or checkout branch
        run: |
          BRANCH_NAME="update-stats"

          if git ls-remote --heads origin "$BRANCH_NAME" | grep -q "$BRANCH_NAME"; then
            git fetch origin "$BRANCH_NAME"
            git checkout "$BRANCH_NAME"
          else
            git checkout -b "$BRANCH_NAME"
          fi

          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Generate stats
        run: python generate_stats.py

      - name: Commit and push changes
        run: |
          git add stats.json

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update stats.json"
          fi

          # Always push the branch (will do nothing if no changes)
          git push -u origin "$BRANCH_NAME"

      - name: Create or update Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_NUMBER=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[0].number')

          PR_BODY="**Updated statistics**

          This PR updates the stats.json file with the latest attendance, win, and performance statistics.

          ---
          *Automatically generated by GitHub Actions*"

          if [ -n "$PR_NUMBER" ]; then
            echo "Updating existing PR #$PR_NUMBER"
            gh pr edit "$PR_NUMBER" --body "$PR_BODY"
          else
            echo "Creating new PR"
            gh pr create \
              --title "Update stats.json" \
              --body "$PR_BODY" \
              --base master
          fi
