name: Deploy Lambda Function

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install AWS CLI
      run: |
        pip install awscli

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Zip Lambda Function
      run: |
        cd lambda/checkin
        zip -r ../../function.zip lambda_function.py

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name checkin --zip-file fileb://function.zip
